packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@parcel/watcher": true
  "@scarf/scarf": true
  "@swc/core": true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true

catalog:
  typescript: ^5.9.2
  zod: ^4.1.5
